### ISSUE TITLE
Trait overriding from the libstd is not supported

### ISSUE THREAD

**Issue by RaitoBezarius** [AeneasVerif/aeneas#133] opened 2024-04-16 14:43 UTC
If I use the libstd's order machinery, I can obtain:

```
❯ nix run github:aeneasverif/aeneas -L -- -backend lean avl_verification.llbc
[Info ] Imported: avl_verification.llbc
[Error] Overriding trait provided methods in trait implementations is not supported yet (overriden methods: lt, le, ge, gt)
Source: '/rustc/d59363ad0b6391b7fc5bbb02c9ccf9300eef3753/library/core/src/cmp.rs', lines 1357:12-1370:13
```

Reproducer: https://github.com/RaitoBezarius/avl-verification/tree/rust-avl-std

cc @Nadrieril

**Comment by Nadrieril** [comment] 2024-04-16 15:31
I'm on it! Duplicate of https://github.com/AeneasVerif/aeneas/issues/70.

**Closed by Nadrieril** 2024-04-16 15:31 UTC
